### ISSUE TITLE
Done dir cannot be empty

### ISSUE THREAD

**Issue by Jonny007-MKD** [mrworf/iceshelf#5]
The comments in iceshelf.sample.conf and README.md say that the done dir can be left empty to disable the copying after a successful operation. Still, I get the warning `Done dir cannot be empty`  and the path points to the default `backup/done/`.

I suggest to replace line 256 in modules/configuration.py by `setting["donedir"] = None`

**Comment by mrworf** [comment]
You're right. All the code is there except the config reader will not accept it. Copy'n'paste issue I think.

**Comment by Jonny007-MKD** [comment]
thanks :)
